Products:

  General:
    notitle: true
    Display vendor description:
      name: display-vendor-description
      type: checkbox
      inline_label: Yes
      help: "If checked and a collection exists with the same handle as the vendor handle, the collection description (and image)&#xA0;will be displayed at the bottom of the product page."

    Enable image lightbox:
      name: enable-image-lightbox
      type: checkbox
      inline_label: Yes

    Enable image zoom:
      name: enable-image-zoom
      type: checkbox
      inline_label: Yes

    Hidden tag prefixes:
      name: hidden-tag-prefixes
      type: text-single
      help: Comma-separated list of tag prefixes to never display on the site. These can be used for creating more complex collection.
      default: "hd,hidden"

    Product Tab Linklist:
      name: product-tab-linklist
      type: linklist

    Secondary Call to Action URL:
      name: secondary-call-to-action-url
      type: text-single
      help: E.g. link to your contact page for customers who want a customised version of your product.

    Show product collections:
      name: show-product-collections
      type: checkbox
      inline_label: Yes

    Show product tags:
      name: show-product-tags
      type: checkbox
      inline_label: Yes

    Show product type:
      name: show-product-type
      type: checkbox
      inline_label: Yes

    Show product vendor:
      name: show-product-vendor
      type: checkbox
      inline_label: Yes

    Show unavailable products:
      name: show-unavailable-products
      type: checkbox
      inline_label: Yes
